# Generated by Django 3.0.2 on 2020-01-26 04:09

from django.db import migrations, models

"""
    ./manage.py makemigration store

    reads all models from models.py and create table schema migration(create table) script
"""

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
