# Generated by Django 3.0.2 on 2020-01-26 04:49

from django.db import migrations, models

"""
    this is migration is added when we added more fields to model book

    migration script will ask for default value for non nullable field, if not given in model class

"""

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'), # since making changes in same model 
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
